using SoulboundEngine.Client.UI.UXMLBindings;
using SoulboundEngine.Registry;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

namespace SoulboundUnityEditor {
	public class UXMLSchemaGenerator : AssetPostprocessor {
		private const string OUTPUT_FILE = "UXMLSchema_Generated.cs";
		private const string OUTPUT_PATH = "Assets/Game/SoulboundEngine/Client/UI/UXMLBindings/Generated/" + OUTPUT_FILE;
		private const string DEFAULT_NAMESPACE = "soulbound";
		private static readonly string[] PROJECT_UXML_ROOTS = {
			"Assets/Game/Content/"
		};
		private static readonly Dictionary<string, Type> BUILT_IN_TYPES = new() {
			["VisualElement"] = typeof(VisualElement),
			["Button"] = typeof(Button),
			["Label"] = typeof(Label),
			["TextField"] = typeof(TextField),
			["Toggle"] = typeof(Toggle),
			["ListView"] = typeof(ListView),
			["ScrollView"] = typeof(ScrollView),
			["Image"] = typeof(Image),
			["Slider"] = typeof(Slider),
			["IntegerField"] = typeof(IntegerField),
			["FloatField"] = typeof(FloatField),
			["DropdownField"] = typeof(DropdownField),
			["Foldout"] = typeof(Foldout),
			["Instance"] = typeof(TemplateContainer)
		};
		private static readonly HashSet<string> DECLARATION_ONLY_TAGS = new() { "Template", "Style" };

		static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom) {
			bool anyUXMLTouched = imported.Concat(deleted).Concat(moved)
				.Any(p => p.EndsWith(".uxml"));
			if (anyUXMLTouched) RegenerateAll();
		}

		[MenuItem("Soulbound/Regenerate UXML Schema")]
		static void RegenerateAll() {
			IEnumerable<string> allUXML = AssetDatabase.FindAssets("t:VisualTreeAsset")
				.Select(AssetDatabase.GUIDToAssetPath)
				.Where(p => p.EndsWith(".uxml"))
				.Where(p => PROJECT_UXML_ROOTS.Any(root => p.StartsWith(root)));

			StringBuilder stringBuilder = new();
			stringBuilder.AppendLine("//");
			stringBuilder.AppendLine("// AUTO-GENERATED BY UXMLSchemaGenerator.cs. DO NOT EDIT BY HAND");
			stringBuilder.AppendLine("//");
			stringBuilder.AppendLine("using SoulboundEngine.Core.Registry;");
			stringBuilder.AppendLine("using UnityEngine.UIElements;");
			stringBuilder.AppendLine();
			stringBuilder.AppendLine("namespace SoulboundEngine.Client.UI.UXMLBindings {");
			stringBuilder.AppendLine("    public static class UXMLSchema_Generated {");
			stringBuilder.AppendLine("        public static void RegisterAll() {");

			foreach (var path in allUXML) {
				string documentId = ToSnakeCase(Path.GetFileNameWithoutExtension(path));
				string renameMessage = AssetDatabase.RenameAsset(path, documentId);
				if (!string.IsNullOrEmpty(renameMessage)) {
					Debug.LogError("[UXMLSchemaGenerator] Failed to rename asset: " + renameMessage);
				}
				XDocument document = XDocument.Load(path);
				HashSet<string> seenInThisDoc = new();

				foreach (var element in document.Descendants().Where(e => e.Attribute("name") != null)) {
					string leaf = element.Attribute("name").Value;
					if (string.IsNullOrEmpty(leaf)) continue;

					Type resolvedType = ResolveClrType(element.Name.LocalName);
					if (resolvedType == null) continue;

					// note: the default namespace is only used for .uxml filed found in the game's Assets files.
					// when modding support is added, keep in mind that the namespace will match the mod namespace
					string id = $"\"{DEFAULT_NAMESPACE}:{documentId}/{leaf}\"";
					if (!Identifier.IsValid(leaf)) {
						Debug.LogWarning($"[UXMLSchemaGenerator] Found invalid UXML schema element identifier: {id}, skipping");
						continue;
					}
					if (!seenInThisDoc.Add(leaf)) {
						Debug.LogError($"[UXMLSchemaGenerator] Duplicate name '{leaf}' in '{path}': "
							+ $"Q<T>(\"{leaf}\") on this document's root is ambiguous. Rename one of them.");
						continue;
					}
					stringBuilder.AppendLine(
						$"            {nameof(UXMLSchema)}.{nameof(UXMLSchema.Register)}({nameof(Identifier)}.{nameof(Identifier.Of)}({id}), typeof({resolvedType.Name}));"
					);
				}
			}

			stringBuilder.AppendLine("        }");
			stringBuilder.AppendLine("    }");
			stringBuilder.AppendLine("}");

			Directory.CreateDirectory(Path.GetDirectoryName(OUTPUT_PATH));
			File.WriteAllText(OUTPUT_PATH, stringBuilder.ToString());
			AssetDatabase.Refresh();
		}

		private static string ToSnakeCase(string s) {
			if (string.IsNullOrEmpty(s)) return s;

			StringBuilder sb = new();
			for (int i = 0; i < s.Length; i++) {
				char c = s[i];
				if (char.IsUpper(c)) {
					bool prevLower = i > 0 && char.IsLower(s[i - 1]);
					bool nextLower = i + 1 < s.Length && char.IsLower(s[i + 1]);
					if (i > 0 && (prevLower || nextLower)) {
						sb.Append('_');
					}
					sb.Append(char.ToLowerInvariant(c));
				} else {
					sb.Append(c);
				}
			}
			return sb.ToString();
		}

		private static Type ResolveClrType(string uxmlTag) {
			string tag = uxmlTag.Contains(':') ? uxmlTag[(uxmlTag.IndexOf(':') + 1)..] : uxmlTag;

			if (DECLARATION_ONLY_TAGS.Contains(tag)) return null;

			if (BUILT_IN_TYPES.TryGetValue(tag, out var builtin)) return builtin;

			var match = AppDomain.CurrentDomain.GetAssemblies()
				.SelectMany(a => { try { return a.GetTypes(); } catch { return Array.Empty<Type>(); } })
				.FirstOrDefault(t => t.Name == tag && typeof(VisualElement).IsAssignableFrom(t));

			return match;
		}
	}
}
